/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author enzov
 */



public class CoachPanel extends javax.swing.JPanel {
    
    
    /**
     * Creates new form CoachPanel
     */
    private TeamManagerGUI parentFrame;
    
    public CoachPanel(TeamManagerGUI parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rosa = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        creaGiocatore = new javax.swing.JButton();
        archivioGiocatori = new javax.swing.JButton();
        suggerisciFormazione = new javax.swing.JButton();
        sessioneMirata = new javax.swing.JButton();
        analisiPerformance = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Benvenuto Allenatore!");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rosa.setBackground(new java.awt.Color(204, 204, 204));
        rosa.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        rosa.setText("Rosa");
        rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosaActionPerformed(evt);
            }
        });

        calendario.setBackground(new java.awt.Color(204, 204, 204));
        calendario.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        calendario.setText("Calendario");
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });

        creaGiocatore.setBackground(new java.awt.Color(204, 204, 204));
        creaGiocatore.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        creaGiocatore.setText("Crea giocatore");
        creaGiocatore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaGiocatoreActionPerformed(evt);
            }
        });

        archivioGiocatori.setBackground(new java.awt.Color(204, 204, 204));
        archivioGiocatori.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        archivioGiocatori.setText("Gestisci Progressi");
        archivioGiocatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivioGiocatoriActionPerformed(evt);
            }
        });

        suggerisciFormazione.setBackground(new java.awt.Color(204, 204, 204));
        suggerisciFormazione.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        suggerisciFormazione.setText("Suggerisci Formazione");

        sessioneMirata.setBackground(new java.awt.Color(204, 204, 204));
        sessioneMirata.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        sessioneMirata.setText("Sessione Mirata");

        analisiPerformance.setBackground(new java.awt.Color(204, 204, 204));
        analisiPerformance.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        analisiPerformance.setText("Confronta Giocatore");
        analisiPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisiPerformanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creaGiocatore, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sessioneMirata, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(archivioGiocatori, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(suggerisciFormazione))
                    .addComponent(analisiPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivioGiocatori, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suggerisciFormazione, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessioneMirata, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creaGiocatore, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analisiPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        // TODO add your handling code here:
        parentFrame.calendarPanel.initCard();
        parentFrame.cardLayout.show(parentFrame.getjPanel1(),"CALENDARPANEL");
    }//GEN-LAST:event_calendarioActionPerformed

    private void rosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosaActionPerformed
        // TODO add your handling code here:
        parentFrame.rosaPanel.initCard();
        parentFrame.cardLayout.show(parentFrame.getjPanel1(),"ROSAPANEL");
    }//GEN-LAST:event_rosaActionPerformed

    private void creaGiocatoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaGiocatoreActionPerformed
        // TODO add your handling code here:
        parentFrame.cardLayout.show(parentFrame.getjPanel1(),"CREATEPANEL");
    }//GEN-LAST:event_creaGiocatoreActionPerformed

    private void archivioGiocatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivioGiocatoriActionPerformed
        // TODO add your handling code here:
        parentFrame.progressPanel.initCard();
        parentFrame.cardLayout.show(parentFrame.getjPanel1(),"PROGRESSPANEL");
    }//GEN-LAST:event_archivioGiocatoriActionPerformed

    private void analisiPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisiPerformanceActionPerformed
        // TODO add your handling code here:
        parentFrame.comparePanel.initCard();
        parentFrame.cardLayout.show(parentFrame.getjPanel1(), "COMPAREPANEL");
    }//GEN-LAST:event_analisiPerformanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisiPerformance;
    private javax.swing.JButton archivioGiocatori;
    private javax.swing.JButton calendario;
    private javax.swing.JButton creaGiocatore;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton rosa;
    private javax.swing.JButton sessioneMirata;
    private javax.swing.JButton suggerisciFormazione;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
